describe('Test full trip', () => {

    it('the full trip', () => {
        cy.visit('http://localhost:3000/')

        cy.fixture('tripInformations').then((tripInformations) => {
            cy.get('[data-testid="searchBar"]')
                .type(tripInformations.startCity+'{enter}')
                .type('{enter}')
            cy.wait(1000)

            cy.location('href').should('include', '/startEndTrip')
            cy.wait(1000)
            cy.get('[data-testid="endCity"]')
                .type(tripInformations.endCity + '{enter}')
                .type('{enter}')
            cy.wait(1000)
            cy.get('[data-testid="startDate"]').click()
            cy.wait(1000)
            cy.get(':nth-child(4) > :nth-child(3) > .mantine-388pmv').click()
            cy.wait(1000)
            cy.get('[data-testid="endDate"]').click()
            cy.wait(1000)
            cy.get(':nth-child(5) > :nth-child(6) > .mantine-DatePicker-day').click()
            cy.wait(1000)
            cy.get('[data-testid="nextStep"]').click()
            cy.wait(1000)
            cy.get('[data-testid="train"]').click()
            cy.wait(1000)
            cy.get('.mantine-ActionIcon-outline').click()
            cy.wait(1000)
            cy.get('[data-testid="goEnjoy"]').click()
            cy.wait(1000)
            cy.get(':nth-child(3) > .mantine-Button-subtle').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > :nth-child(7) > .mantine-ActionIcon-outline').click()
            cy.wait(1000)

            cy.get('[data-testid="goSleep"]').click()
            cy.wait(1000)
            cy.get(':nth-child(3) > .mantine-Button-subtle').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > :nth-child(7) > .mantine-ActionIcon-outline').click()
            cy.wait(1000)
            cy.get('[data-testid="goEat"]').click()
            cy.wait(1000)

            cy.get(':nth-child(3) > .mantine-Button-subtle').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > :nth-child(7) > .mantine-ActionIcon-outline').click()
            cy.wait(1000)
            cy.get('[data-testid="goDrink"]').click()
            cy.wait(1000)

            cy.get(':nth-child(3) > .mantine-Button-subtle').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > :nth-child(7) > .mantine-ActionIcon-outline').click()
            cy.wait(1000)
            cy.get('[data-testid="enjoyArrival"]').click()
            cy.wait(1000)


            cy.get(':nth-child(3) > .mantine-Button-subtle').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > :nth-child(7) > .mantine-ActionIcon-outline').click()
            cy.wait(1000)
            cy.get('[data-testid="sleepArrival"]').click()
            cy.wait(1000)


            cy.get(':nth-child(3) > .mantine-Button-subtle').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > :nth-child(7) > .mantine-ActionIcon-outline').click()
            cy.wait(1000)
            cy.get('[data-testid="goEat"]').click()
            cy.wait(1000)

            cy.get(':nth-child(3) > .mantine-Button-subtle').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > :nth-child(7) > .mantine-ActionIcon-outline').click()
            cy.wait(1000)
            cy.get('[data-testid="drinkArrival"]').click()
            cy.wait(1000)

            cy.get(':nth-child(3) > .mantine-Button-subtle').click()
            cy.wait(1000)
            cy.get(':nth-child(1) > :nth-child(7) > .mantine-ActionIcon-outline').click()
            cy.wait(1000)
            cy.get('[data-testid="ResumeTrip"]').click()
            cy.wait(1000)
        })
    })
})